mols: ['O1C=CN=C1']
upperbound_tr: 0.95
upperbound_dr: 0.90
property_value: -6
lr_train: 1e-05
lr_dream: .01
test_model: 0
plot_transform: 0
n_heads: 12

data_preprocess:
  smiles_file: datasets/training_set.txt

data:
  num_train: 122039
  num_dream: 100000

model:
  num_of_neurons_layer1: 500
  num_of_neurons_layer2: 500
  num_of_neurons_layer3: 460

training:
  num_epochs: 100000
  batch_size: 10

dreaming:
  batch_size: 1
  num_epochs: 2000