mols: ['O1C=CN=C1']
upperbound_tr: 0.95
upperbound_dr: 0.90
property_value: 6
lr_train: 1e-06
lr_dream: 0.01
test_model: 0
plot_transform: 0
n_heads: 3

data_preprocess:
  smiles_file: datasets/0SelectedSMILES_QM9.txt

data:
  num_train: 1000
  num_dream: 500

model:
  num_of_neurons_layer1: 500
  num_of_neurons_layer2: 500
  num_of_neurons_layer3: -1

training:
  num_epochs: 200
  batch_size: 1

dreaming:
  batch_size: 1
  num_epochs: 200